language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '8.10'
script:
  - npm test
after_success:
  - npm run coveralls
  - npm run semantic-release
before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
